version: '3'
services:
  back:
    container_name: back
    build: ./server
    env_file: ./server/.env
    ports:
      - '3000:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
